global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: true

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'team-email'
  routes:
  - match:
      severity: critical
    receiver: 'team-pager'
    continue: true
    repeat_interval: 1h
  - match:
      severity: warning
    receiver: 'team-email'
    continue: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'team-email'
    email_configs:
    - to: 'team@example.com'
      send_resolved: true

  - name: 'team-pager'
    webhook_configs:
    - url: 'http://pager-webhook:8080/notify'
      send_resolved: true
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
      channel: '#alerts'
      send_resolved: true
