# Τροποποιημένο αρχείο monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      scheme: http
      timeout: 10s
      api_version: v2

rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # ΑΦΑΙΡΟΥΜΕ ή ΔΙΟΡΘΩΝΟΥΜΕ το job που προσπαθεί να κάνει scrape το Kafka απευθείας
  # - job_name: kafka
  #   static_configs:
  #     - targets:
  #       - 'kafka:9093'  # ΛΑΘΟΣ - το Kafka δεν εκθέτει HTTP metrics
  #   metrics_path: /metrics

  # ΣΩΣΤΟ job για Kafka μέσω JMX Exporter
  - job_name: kafka-jmx
    static_configs:
      - targets:
        - 'kafka-jmx-exporter:7071'  # Ξεχωριστό service για JMX Exporter
    metrics_path: /metrics

  - job_name: flink
    static_configs:
      - targets:
        - 'flink-jobmanager:9249'
        - 'flink-taskmanager:9249'
    metrics_path: /metrics

  - job_name: api-gateway
    static_configs:
      - targets:
        - 'api-gateway:8080'
    metrics_path: /actuator/prometheus

  - job_name: frontend
    static_configs:
      - targets:
        - 'frontend:80'
    metrics_path: /metrics

  - job_name: node-exporter
    static_configs:
      - targets:
        - 'node-exporter:9100'
    metrics_path: /metrics